sudo: true
language: python
python:
  - "2.7"
env:
  - TOX_ENV=docs
  - TOX_ENV=pep8
  - TOX_ENV=validate-local-blueprint
  - TOX_ENV=validate-multicloud-blueprint
  - TOX_ENV=execute-local-blueprint
  - TOX_ENV=validate-bind9-blueprint
  - TOX_ENV=py27-core-integration

install:
  - ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - chmod +x ~/.ssh/authorized_keys
  - echo -e "StrictHostKeyChecking no\n" >> ~/.ssh/conf
  - git clone --depth=50 --branch=master https://github.com/aria-tosca/aria-examples.git aria-examples
  - pip install tox

script:
  - tox -e $TOX_ENV
# commented until aria-core will be at PYPI
#  - pip install -e .
#  - pip install aria-core
#  - aria init -b multicloud-id -p aria-examples/multicloud-blueprint.yaml -i aria-examples/inputs/multicloud.yaml.template --install-plugins --debug
